---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: centos65
    driver:
      box: learningchef/centos65
      box_url: learningchef/centos65
      network:
      - ["private_network", {ip: "192.168.33.35"}]
      synced_folders:
      - ["./chef-repo", "/chef-repo"] # [dir on the host, dir on the guest node]

suites:
  # - name: default
  - name: node
    attributes:
